name: proton-demo-ecommerce
volumes:
  redpanda: null
services:
  proton:
    image: d.timeplus.com/timeplus-io/proton:latest
    pull_policy: always
    ports:
      #  - 3218:3218 #http port for JDBC driver, default streaming mode
      - 8123:8123 #http port for JDBC driver, default batch mode

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.15
    command:
      - redpanda start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --smp 1
      - --memory 1G
      - --mode dev-container
    volumes:
      - redpanda:/var/lib/redpanda/data

  console:
    image: docker.redpanda.com/redpandadata/console:v2.3.5
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda

  owl-shop:
    image: quay.io/cloudhut/owl-shop:latest
    #platform: 'linux/amd64'
    environment:
      - SHOP_KAFKA_BROKERS=redpanda:9092
      - SHOP_KAFKA_TOPICREPLICATIONFACTOR=1
      - SHOP_TRAFFIC_INTERVAL_RATE=1
      - SHOP_TRAFFIC_INTERVAL_DURATION=0.1s
    depends_on:
      - redpanda
